### ISSUE TITLE
missing sparse_array.py

### ISSUE THREAD

**Issue by codedragon** [UWPCE-PythonCert/IntroPython2016#124]
IntroPython2016/Solutions/Session08 has the tests for SparseArray, but no file containing the actual SparseArray.

**Comment by PythonCHB** [comment]
hmm -- I wanted to put the tests in first, but your'e right, I can't find it either -- or trapz.

let's keep looking! Or re-write it!

**Comment by PythonCHB** [comment]
Found it!

Pushed to class repo.

But I haven't actually run them, or reviewed them.

So if you have some time -- give them a review.
